services:
  postgres_clinic:
    image: postgres:latest
    container_name: resqueue_pg_clinic
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: resqueue_clinic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_clinic:/var/lib/postgresql/data
    networks:
      - resqueue_network

#  postgres_vaccine:
#    image: postgres:latest
#    container_name: resqueue_pg_vaccine
#    restart: always
#    environment:
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#      POSTGRES_DB: resqueue_vaccine
#    ports:
#      - "5433:5432"
#    volumes:
#      - postgres_data_vaccine:/var/lib/postgresql/data
#    networks:
#      - resqueue_network

volumes:
  postgres_data_clinic:
    name: postgres_data_clinic
#  postgres_data_vaccine:
#    name: postgres_data_vaccine

networks:
  resqueue_network:
    name: resqueue_network
    driver: bridge
