services:
  postgres_clinic:
    image: postgres:latest
    container_name: resqueue_pg_clinic
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: resqueue_clinic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_clinic:/var/lib/postgresql/data
    networks:
      - clinic_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d resqueue_clinic"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    container_name: resqueue_clinic_app
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DATABASE_URL: jdbc:postgresql://localhost:5432/resqueue_clinic
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
    depends_on:
      postgres_clinic:
        condition: service_healthy

volumes:
  postgres_data_clinic:
    name: postgres_data_clinic

networks:
  clinic_network:
    driver: bridge
