server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: RESQUEUE-CLINIC

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_BASE_ISSUER_URL:http://localhost:9000}/realms/resqueue

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/resqueue_clinic}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /clinic/v3/api-docs
  swagger-ui:
    enabled: true
    path: /docs
    config-url: /clinic/v3/api-docs/swagger-config
    urls:
      - name: clinic-service
        url: /clinic/v3/api-docs
