server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: resqueue-clinic
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/resqueue

  datasource:
    url: jdbc:postgresql://localhost:5432/resqueue_clinic
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    baseline-on-migrate: true
    enabled: true

  springdoc:
    api-docs:
      enabled: true
      path: /clinic/v3/api-docs
    swagger-ui:
      enabled: true
      path: /docs
      config-url: /clinic/v3/api-docs/swagger-config
      urls:
        - name: clinic-service
          url: /clinic/v3/api-docs