name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker stop clinic || true
            docker rm clinic || true
            docker rmi ${{ secrets.DOCKERHUB_REPOSITORY }}:latest || true
            docker pull ${{ secrets.DOCKERHUB_REPOSITORY }}:latest
            docker run -d --network host --name clinic \
              --restart=unless-stopped \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e eureka.environment=prod \
              -e AUTH_BASE_URL=${{ secrets.AUTH_BASE_URL }} \
              -e KC_BASE_ISSUER_URL=${{ secrets.KC_BASE_ISSUER_URL }} \
              -e EUREKA_URL=${{ secrets.EUREKA_URL }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
              -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
              ${{ secrets.DOCKERHUB_REPOSITORY }}:latest
